from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

# uri = "mongodb+srv://gega:gega2001@cluster0.v7rln8c.mongodb.net/?retryWrites=true&w=majority"
uri = "mongodb://localhost:27017"
client = MongoClient(uri, server_api=ServerApi('1'))
db = client["linkedIn"]
collection_name="jobs"
collection= db[collection_name]

jobs = [
    {
        "job_title": "Graphic Designer",
        "job_description": "Design visually appealing graphics for marketing and web projects.",
        "company": "DesignPros Creative Agency",
        "job_type": "Part-Time",
        "location": "Remote",
        "salary": "Hourly rate, commensurate with experience",
        "application_deadline": "2023-11-30",
        "application_process": "Submit your portfolio and resume to designjobs@designpros.com",
        "job_requirements": ["Proficient in Adobe Creative Suite", "Strong design portfolio"],
        "desired_skills": ["Illustrator", "Photoshop"],
        "job_category": "Design",
        "date_posted": "2023-10-14",
        "job_status": "Open",
        "contact_information": "Jane Smith (Creative Director), janesmith@designpros.com",
        "tags": ["graphic design", "part-time", "remote"],
        "posted_by": "user101",
        "application_count": 12,
        "job_id": "job101"
    },
    {
        "job_title": "Sales Representative",
        "job_description": "Sell our products and services to potential clients.",
        "company": "SalesForce Inc.",
        "job_type": "Full-Time",
        "location": "Chicago, IL",
        "salary": "$60,000 - $80,000 per year",
        "application_deadline": "2023-11-20",
        "application_process": "Apply online or send your resume to hr@salesforce.com",
        "job_requirements": ["High school diploma or equivalent", "Sales experience"],
        "desired_skills": ["Negotiation", "Communication"],
        "job_category": "Sales",
        "date_posted": "2023-10-14",
        "job_status": "Open",
        "contact_information": "Mark Johnson (HR Manager), markjohnson@salesforce.com",
        "tags": ["sales", "full-time", "Chicago"],
        "posted_by": "user202",
        "application_count": 5,
        "job_id": "job202"
    },
    {
        "job_title": "Customer Support Specialist",
        "job_description": "Provide excellent customer support and resolve customer issues.",
        "company": "Supportive Services Ltd.",
        "job_type": "Full-Time",
        "location": "Austin, TX",
        "salary": "$45,000 - $55,000 per year",
        "application_deadline": "2023-11-22",
        "application_process": "Submit your application through our website.",
        "job_requirements": ["High school diploma or equivalent", "Customer service experience"],
        "desired_skills": ["Problem-solving", "Communication"],
        "job_category": "Customer Service",
        "date_posted": "2023-10-14",
        "job_status": "Open",
        "contact_information": "Sarah Davis (HR Manager), sarahdavis@supportiveservices.com",
        "tags": ["customer support", "full-time", "Austin"],
        "posted_by": "user303",
        "application_count": 9,
        "job_id": "job303"
    },
    {
        "job_title": "Project Manager",
        "job_description": "Manage projects and ensure their successful completion.",
        "company": "Project Masters LLC",
        "job_type": "Full-Time",
        "location": "Boston, MA",
        "salary": "$80,000 - $100,000 per year",
        "application_deadline": "2023-11-25",
        "application_process": "Apply through our website.",
        "job_requirements": ["Bachelor's degree", "Project management experience"],
        "desired_skills": ["Leadership", "Organizational skills"],
        "job_category": "Management",
        "date_posted": "2023-10-15",
        "job_status": "Open",
        "contact_information": "Michael Wilson (HR Manager), michaelwilson@projectmasters.com",
        "tags": ["project management", "full-time", "Boston"],
        "posted_by": "user404",
        "application_count": 10,
        "job_id": "job404"
    },
    {
        "job_title": "Content Writer",
        "job_description": "Create engaging and informative content for various platforms.",
        "company": "ContentCreators Media",
        "job_type": "Contract",
        "location": "Remote",
        "salary": "$25 - $35 per hour",
        "application_deadline": "2023-11-28",
        "application_process": "Submit your writing samples to hr@contentcreators.com",
        "job_requirements": ["Bachelor's degree in English or related field", "Writing experience"],
        "desired_skills": ["Copywriting", "SEO"],
        "job_category": "Writing",
        "date_posted": "2023-10-15",
        "job_status": "Open",
        "contact_information": "Emily Reed (HR Manager), emilyreed@contentcreators.com",
        "tags": ["content writing", "contract", "remote"],
        "posted_by": "user505",
        "application_count": 7,
        "job_id": "job505"
    },
    {
        "job_title": "Financial Analyst",
        "job_description": "Analyze financial data and provide insights for decision-making.",
        "company": "Financial Insights Corp.",
        "job_type": "Full-Time",
        "location": "Chicago, IL",
        "salary": "$70,000 - $90,000 per year",
        "application_deadline": "2023-11-30",
        "application_process": "Submit your resume and cover letter to hr@financialinsights.com",
        "job_requirements": ["Bachelor's degree in Finance", "Financial analysis experience"],
        "desired_skills": ["Excel", "Financial modeling"],
        "job_category": "Finance",
        "date_posted": "2023-10-15",
        "job_status": "Open",
        "contact_information": "Karen Brown (HR Manager), karenbrown@financialinsights.com",
        "tags": ["financial analysis", "full-time", "Chicago"],
        "posted_by": "user606",
        "application_count": 11,
        "job_id": "job606"
    },
    {
        "job_title": "UI/UX Designer",
        "job_description": "Design user-friendly interfaces and enhance user experiences.",
        "company": "UIX Innovations",
        "job_type": "Full-Time",
        "location": "San Francisco, CA",
        "salary": "$75,000 - $95,000 per year",
        "application_deadline": "2023-12-05",
        "application_process": "Send your portfolio and resume to hr@uixinnovations.com",
        "job_requirements": ["Bachelor's degree in Design", "UI/UX design experience"],
        "desired_skills": ["Wireframing", "Prototyping"],
        "job_category": "Design",
        "date_posted": "2023-10-16",
        "job_status": "Open",
        "contact_information": "Alex Miller (HR Manager), alexmiller@uixinnovations.com",
        "tags": ["ui/ux design", "full-time", "San Francisco"],
        "posted_by": "user707",
        "application_count": 14,
        "job_id": "job707"
    },
    {
        "job_title": "HR Specialist",
        "job_description": "Manage human resources functions and support employee needs.",
        "company": "HR Pro Services",
        "job_type": "Full-Time",
        "location": "New York, NY",
        "salary": "$60,000 - $80,000 per year",
        "application_deadline": "2023-12-10",
        "application_process": "Apply online or send your resume to hr@hrproservices.com",
        "job_requirements": ["Bachelor's degree in HR or related field", "HR experience"],
        "desired_skills": ["Recruitment", "Employee relations"],
        "job_category": "Human Resources",
        "date_posted": "2023-10-16",
        "job_status": "Open",
        "contact_information": "Olivia Davis (HR Manager), oliviadavis@hrproservices.com",
        "tags": ["hr specialist", "full-time", "New York"],
        "posted_by": "user808",
        "application_count": 6,
        "job_id": "job808"
    },
    {
        "job_title": "Sales Manager",
        "job_description": "Lead the sales team and achieve sales targets.",
        "company": "Sales Masters Inc.",
        "job_type": "Full-Time",
        "location": "Los Angeles, CA",
        "salary": "$90,000 - $120,000 per year",
        "application_deadline": "2023-12-15",
        "application_process": "Submit your application on our website.",
        "job_requirements": ["Bachelor's degree", "Sales management experience"],
        "desired_skills": ["Sales strategy", "Team leadership"],
        "job_category": "Sales",
        "date_posted": "2023-10-16",
        "job_status": "Open",
        "contact_information": "Paul Anderson (HR Manager), paulanderson@salesmasters.com",
        "tags": ["sales management", "full-time", "Los Angeles"],
        "posted_by": "user909",
        "application_count": 9,
        "job_id": "job909"
    },
    {
        "job_title": "Quality Assurance Tester",
        "job_description": "Test software applications to ensure quality and functionality.",
        "company": "QualityTech Solutions",
        "job_type": "Full-Time",
        "location": "Austin, TX",
        "salary": "$50,000 - $70,000 per year",
        "application_deadline": "2023-12-20",
        "application_process": "Send your resume and cover letter to hr@qualitytechsolutions.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "QA testing experience"],
        "desired_skills": ["Manual testing", "Bug tracking"],
        "job_category": "Technology",
        "date_posted": "2023-10-17",
        "job_status": "Open",
        "contact_information": "Sarah Wilson (HR Manager), sarahwilson@qualitytechsolutions.com",
        "tags": ["qa testing", "full-time", "Austin"],
        "posted_by": "user1010",
        "application_count": 8,
        "job_id": "job1010"
    },
    {
        "job_title": "Data Scientist",
        "job_description": "Use data to uncover insights and drive decision-making.",
        "company": "Data Insights Plus",
        "job_type": "Full-Time",
        "location": "Seattle, WA",
        "salary": "$100,000 - $130,000 per year",
        "application_deadline": "2023-12-10",
        "application_process": "Submit your CV to hr@dataplus.com",
        "job_requirements": ["Master's degree in Data Science", "Data analysis experience"],
        "desired_skills": ["Machine Learning", "Data Visualization"],
        "job_category": "Data Science",
        "date_posted": "2023-10-20",
        "job_status": "Open",
        "contact_information": "Laura Martinez (HR Manager), lauramartinez@dataplus.com",
        "tags": ["data science", "full-time", "Seattle"],
        "posted_by": "user111",
        "application_count": 8,
        "job_id": "job111"
    },
    {
        "job_title": "Content Marketing Specialist",
        "job_description": "Create and manage content marketing strategies.",
        "company": "ContentHub Marketing",
        "job_type": "Full-Time",
        "location": "Chicago, IL",
        "salary": "$65,000 - $85,000 per year",
        "application_deadline": "2023-12-15",
        "application_process": "Apply online through our website.",
        "job_requirements": ["Bachelor's degree in Marketing", "Content marketing experience"],
        "desired_skills": ["SEO", "Content Strategy"],
        "job_category": "Marketing",
        "date_posted": "2023-10-20",
        "job_status": "Open",
        "contact_information": "James Smith (HR Manager), jamessmith@contenthub.com",
        "tags": ["content marketing", "full-time", "Chicago"],
        "posted_by": "user222",
        "application_count": 6,
        "job_id": "job222"
    },
    {
        "job_title": "iOS App Developer",
        "job_description": "Design and develop iOS applications for our clients.",
        "company": "AppCrafters LLC",
        "job_type": "Full-Time",
        "location": "San Jose, CA",
        "salary": "$85,000 - $110,000 per year",
        "application_deadline": "2023-12-05",
        "application_process": "Send your portfolio and resume to iosjobs@appcrafters.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "iOS app development experience"],
        "desired_skills": ["Swift", "UI/UX Design"],
        "job_category": "Technology",
        "date_posted": "2023-10-21",
        "job_status": "Open",
        "contact_information": "Michael Brown (HR Manager), michaelbrown@appcrafters.com",
        "tags": ["iOS development", "full-time", "San Jose"],
        "posted_by": "user333",
        "application_count": 10,
        "job_id": "job333"
    },
    {
        "job_title": "HR Coordinator",
        "job_description": "Assist in HR functions and support employees.",
        "company": "HR Assist Inc.",
        "job_type": "Part-Time",
        "location": "Miami, FL",
        "salary": "Hourly rate, commensurate with experience",
        "application_deadline": "2023-12-20",
        "application_process": "Submit your application online.",
        "job_requirements": ["High school diploma or equivalent", "HR experience"],
        "desired_skills": ["Recruitment", "Employee Benefits"],
        "job_category": "Human Resources",
        "date_posted": "2023-10-21",
        "job_status": "Open",
        "contact_information": "Maria Lopez (HR Manager), marialopez@hrassist.com",
        "tags": ["hr coordinator", "part-time", "Miami"],
        "posted_by": "user444",
        "application_count": 4,
        "job_id": "job444"
    },
    {
        "job_title": "Frontend Developer",
        "job_description": "Create user interfaces and enhance user experiences.",
        "company": "UI Wizards Tech",
        "job_type": "Full-Time",
        "location": "Denver, CO",
        "salary": "$75,000 - $95,000 per year",
        "application_deadline": "2023-12-25",
        "application_process": "Apply by sending your resume to hr@uiwizards.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "Frontend development experience"],
        "desired_skills": ["React", "Responsive Design"],
        "job_category": "Technology",
        "date_posted": "2023-10-22",
        "job_status": "Open",
        "contact_information": "Sophia Taylor (HR Manager), sophiataylor@uiwizards.com",
        "tags": ["frontend development", "full-time", "Denver"],
        "posted_by": "user555",
        "application_count": 7,
        "job_id": "job555"
    },
    {
        "job_title": "Digital Marketing Manager",
        "job_description": "Lead digital marketing efforts and campaigns.",
        "company": "DigitalDreams Marketing",
        "job_type": "Full-Time",
        "location": "Austin, TX",
        "salary": "$90,000 - $120,000 per year",
        "application_deadline": "2023-12-30",
        "application_process": "Submit your CV and cover letter to hr@digitaldreams.com",
        "job_requirements": ["Bachelor's degree in Marketing", "Digital marketing experience"],
        "desired_skills": ["SEO", "Paid Advertising"],
        "job_category": "Marketing",
        "date_posted": "2023-10-22",
        "job_status": "Open",
        "contact_information": "Eric Robinson (HR Manager), ericrobinson@digitaldreams.com",
        "tags": ["digital marketing", "full-time", "Austin"],
        "posted_by": "user666",
        "application_count": 12,
        "job_id": "job666"
    },
    {
        "job_title": "Network Administrator",
        "job_description": "Manage and maintain network infrastructure.",
        "company": "NetWorks Inc.",
        "job_type": "Full-Time",
        "location": "San Diego, CA",
        "salary": "$70,000 - $90,000 per year",
        "application_deadline": "2023-12-12",
        "application_process": "Apply through our website.",
        "job_requirements": ["Bachelor's degree in IT", "Network administration experience"],
        "desired_skills": ["Cisco", "Firewall Management"],
        "job_category": "Technology",
        "date_posted": "2023-10-23",
        "job_status": "Open",
        "contact_information": "Robert Clark (HR Manager), robertclark@networks.com",
        "tags": ["network administration", "full-time", "San Diego"],
        "posted_by": "user777",
        "application_count": 9,
        "job_id": "job777"
    },
    {
        "job_title": "Event Coordinator",
        "job_description": "Plan and execute events for our organization.",
        "company": "EventPros Organization",
        "job_type": "Full-Time",
        "location": "Los Angeles, CA",
        "salary": "$55,000 - $75,000 per year",
        "application_deadline": "2023-12-05",
        "application_process": "Submit your application on our website.",
        "job_requirements": ["Bachelor's degree in Event Management", "Event planning experience"],
        "desired_skills": ["Event Marketing", "Vendor Management"],
        "job_category": "Event Management",
        "date_posted": "2023-10-23",
        "job_status": "Open",
        "contact_information": "Sarah Moore (HR Manager), sarahmoore@eventpros.com",
        "tags": ["event planning", "full-time", "Los Angeles"],
        "posted_by": "user888",
        "application_count": 5,
        "job_id": "job888"
    },
    {
        "job_title": "Business Analyst",
        "job_description": "Analyze business processes and recommend improvements.",
        "company": "BizSolutions Ltd.",
        "job_type": "Full-Time",
        "location": "New York, NY",
        "salary": "$80,000 - $100,000 per year",
        "application_deadline": "2023-12-02",
        "application_process": "Apply by sending your resume to hr@bizsolutions.com",
        "job_requirements": ["Bachelor's degree in Business", "Business analysis experience"],
        "desired_skills": ["Data Analysis", "Process Mapping"],
        "job_category": "Business Analysis",
        "date_posted": "2023-10-24",
        "job_status": "Open",
        "contact_information": "Jessica Allen (HR Manager), jessicaallen@bizsolutions.com",
        "tags": ["business analysis", "full-time", "New York"],
        "posted_by": "user999",
        "application_count": 11,
        "job_id": "job999"
    },
    {
        "job_title": "Registered Nurse",
        "job_description": "Provide patient care and support in a hospital setting.",
        "company": "HealthCare Plus",
        "job_type": "Full-Time",
        "location": "Houston, TX",
        "salary": "$60,000 - $80,000 per year",
        "application_deadline": "2023-12-08",
        "application_process": "Submit your nursing license and resume to hr@healthcareplus.com",
        "job_requirements": ["RN license", "Clinical experience"],
        "desired_skills": ["Patient care", "Medical knowledge"],
        "job_category": "Healthcare",
        "date_posted": "2023-10-25",
        "job_status": "Open",
        "contact_information": "Lisa Johnson (HR Manager), lisajohnson@healthcareplus.com",
        "tags": ["registered nurse", "full-time", "Houston"],
        "posted_by": "user1011",
        "application_count": 8,
        "job_id": "job1011"
    },
    {
        "job_title": "Chef de Cuisine",
        "job_description": "Lead the kitchen team and create culinary delights.",
        "company": "Gourmet Eats Restaurant",
        "job_type": "Full-Time",
        "location": "San Francisco, CA",
        "salary": "$70,000 - $90,000 per year",
        "application_deadline": "2023-12-12",
        "application_process": "Send your culinary portfolio to hr@gourmeteats.com",
        "job_requirements": ["Culinary degree", "Chef experience"],
        "desired_skills": ["Menu creation", "Culinary innovation"],
        "job_category": "Culinary",
        "date_posted": "2023-10-25",
        "job_status": "Open",
        "contact_information": "David Smith (HR Manager), davidsmith@gourmeteats.com",
        "tags": ["chef", "full-time", "San Francisco"],
        "posted_by": "user1012",
        "application_count": 6,
        "job_id": "job1012"
    },
    {
        "job_title": "High School Teacher",
        "job_description": "Educate and inspire high school students in your subject area.",
        "company": "Academic Excellence School",
        "job_type": "Full-Time",
        "location": "New York, NY",
        "salary": "$50,000 - $70,000 per year",
        "application_deadline": "2023-12-10",
        "application_process": "Submit your teaching credentials and resume to hr@academicschool.com",
        "job_requirements": ["Bachelor's degree in Education", "Teaching certification"],
        "desired_skills": ["Classroom management", "Lesson planning"],
        "job_category": "Education",
        "date_posted": "2023-10-26",
        "job_status": "Open",
        "contact_information": "Emily Harris (HR Manager), emilyharris@academicschool.com",
        "tags": ["high school teacher", "full-time", "New York"],
        "posted_by": "user1013",
        "application_count": 7,
        "job_id": "job1013"
    },
    {
        "job_title": "Marketing Analyst",
        "job_description": "Analyze marketing data and trends to inform strategies.",
        "company": "Market Trends Consulting",
        "job_type": "Full-Time",
        "location": "Los Angeles, CA",
        "salary": "$55,000 - $75,000 per year",
        "application_deadline": "2023-12-05",
        "application_process": "Apply online through our website.",
        "job_requirements": ["Bachelor's degree in Marketing", "Marketing analysis experience"],
        "desired_skills": ["Data Analysis", "Market Research"],
        "job_category": "Marketing",
        "date_posted": "2023-10-26",
        "job_status": "Open",
        "contact_information": "John Anderson (HR Manager), johnanderson@markettrends.com",
        "tags": ["marketing analysis", "full-time", "Los Angeles"],
        "posted_by": "user1014",
        "application_count": 6,
        "job_id": "job1014"
    },
    {
        "job_title": "Mechanical Engineer",
        "job_description": "Design and develop mechanical systems and products.",
        "company": "Machineworks Engineering",
        "job_type": "Full-Time",
        "location": "Chicago, IL",
        "salary": "$70,000 - $90,000 per year",
        "application_deadline": "2023-12-15",
        "application_process": "Submit your engineering portfolio to hr@machineworks.com",
        "job_requirements": ["Bachelor's degree in Mechanical Engineering", "Mechanical engineering experience"],
        "desired_skills": ["CAD Design", "Product Development"],
        "job_category": "Engineering",
        "date_posted": "2023-10-27",
        "job_status": "Open",
        "contact_information": "Sarah Davis (HR Manager), sarahdavis@machineworks.com",
        "tags": ["mechanical engineering", "full-time", "Chicago"],
        "posted_by": "user1015",
        "application_count": 9,
        "job_id": "job1015"
    },
    {
        "job_title": "Financial Advisor",
        "job_description": "Provide financial advice and investment strategies to clients.",
        "company": "Financial Insight Advisors",
        "job_type": "Full-Time",
        "location": "Denver, CO",
        "salary": "$75,000 - $100,000 per year",
        "application_deadline": "2023-12-18",
        "application_process": "Send your financial advisor certification and resume to hr@financialinsight.com",
        "job_requirements": ["Certified Financial Planner (CFP)", "Financial advising experience"],
        "desired_skills": ["Investment Planning", "Risk Assessment"],
        "job_category": "Finance",
        "date_posted": "2023-10-27",
        "job_status": "Open",
        "contact_information": "Daniel White (HR Manager), danielwhite@financialinsight.com",
        "tags": ["financial advisor", "full-time", "Denver"],
        "posted_by": "user1016",
        "application_count": 8,
        "job_id": "job1016"
    },
    {
        "job_title": "Graphic Artist",
        "job_description": "Create visually stunning artwork for various projects.",
        "company": "Artistry Creations",
        "job_type": "Contract",
        "location": "Remote",
        "salary": "Project-based compensation",
        "application_deadline": "2023-12-22",
        "application_process": "Submit your portfolio to hr@artistrycreations.com",
        "job_requirements": ["Graphic design experience", "Strong portfolio"],
        "desired_skills": ["Illustration", "Digital Art"],
        "job_category": "Art and Design",
        "date_posted": "2023-10-28",
        "job_status": "Open",
        "contact_information": "Olivia Smith (HR Manager), oliviasmith@artistrycreations.com",
        "tags": ["graphic art", "contract", "remote"],
        "posted_by": "user1017",
        "application_count": 5,
        "job_id": "job1017"
    },
    {
        "job_title": "Dental Assistant",
        "job_description": "Assist dentists in providing patient care and maintaining the dental office.",
        "company": "Bright Smiles Dental Clinic",
        "job_type": "Full-Time",
        "location": "Miami, FL",
        "salary": "$30,000 - $40,000 per year",
        "application_deadline": "2023-12-20",
        "application_process": "Send your resume and dental assistant certification to hr@brightsmiles.com",
        "job_requirements": ["Dental assistant certification", "Dental office experience"],
        "desired_skills": ["Patient care", "Dental procedures"],
        "job_category": "Healthcare",
        "date_posted": "2023-10-28",
        "job_status": "Open",
        "contact_information": "Laura Rodriguez (HR Manager), laurarodriguez@brightsmiles.com",
        "tags": ["dental assistant", "full-time", "Miami"],
        "posted_by": "user1018",
        "application_count": 7,
        "job_id": "job1018"
    },
    {
        "job_title": "Legal Assistant",
        "job_description": "Provide legal support and assist attorneys in their work.",
        "company": "Legal Solutions Group",
        "job_type": "Full-Time",
        "location": "San Diego, CA",
        "salary": "$50,000 - $70,000 per year",
        "application_deadline": "2023-12-25",
        "application_process": "Submit your legal assistant certification and resume to hr@legalsolutions.com",
        "job_requirements": ["Legal assistant certification", "Legal office experience"],
        "desired_skills": ["Legal research", "Document preparation"],
        "job_category": "Legal",
        "date_posted": "2023-10-29",
        "job_status": "Open",
        "contact_information": "John Smith (HR Manager), johnsmith@legalsolutions.com",
        "tags": ["legal assistant", "full-time", "San Diego"],
        "posted_by": "user1019",
        "application_count": 6,
        "job_id": "job1019"
    },
    {
        "job_title": "Environmental Scientist",
        "job_description": "Research and analyze the environment to address ecological issues.",
        "company": "EcoSolutions Research Institute",
        "job_type": "Full-Time",
        "location": "Portland, OR",
        "salary": "$60,000 - $80,000 per year",
        "application_deadline": "2023-12-08",
        "application_process": "Submit your environmental science degree and resume to hr@ecosolutions.com",
        "job_requirements": ["Bachelor's degree in Environmental Science", "Environmental research experience"],
        "desired_skills": ["Field research", "Data analysis"],
        "job_category": "Environmental Science",
        "date_posted": "2023-11-01",
        "job_status": "Open",
        "contact_information": "Sarah Green (HR Manager), sarahgreen@ecosolutions.com",
        "tags": ["environmental science", "full-time", "Portland"],
        "posted_by": "user1020",
        "application_count": 8,
        "job_id": "job1020"
    },
    {
        "job_title": "Electrician",
        "job_description": "Install, repair, and maintain electrical systems and equipment.",
        "company": "PowerTech Electrical Services",
        "job_type": "Full-Time",
        "location": "Houston, TX",
        "salary": "$50,000 - $70,000 per year",
        "application_deadline": "2023-12-12",
        "application_process": "Send your electrician certification and resume to hr@powertech.com",
        "job_requirements": ["Electrician certification", "Electrical work experience"],
        "desired_skills": ["Wiring", "Electrical troubleshooting"],
        "job_category": "Skilled Trades",
        "date_posted": "2023-11-01",
        "job_status": "Open",
        "contact_information": "David Johnson (HR Manager), davidjohnson@powertech.com",
        "tags": ["electrician", "full-time", "Houston"],
        "posted_by": "user1021",
        "application_count": 6,
        "job_id": "job1021"
    },
    {
        "job_title": "Fashion Designer",
        "job_description": "Create innovative clothing designs and fashion collections.",
        "company": "StyleMakers Fashion Studio",
        "job_type": "Full-Time",
        "location": "New York, NY",
        "salary": "$55,000 - $75,000 per year",
        "application_deadline": "2023-12-10",
        "application_process": "Submit your fashion design portfolio and resume to hr@stylemakers.com",
        "job_requirements": ["Fashion design degree", "Fashion design experience"],
        "desired_skills": ["Sketching", "Fabric selection"],
        "job_category": "Fashion Design",
        "date_posted": "2023-11-02",
        "job_status": "Open",
        "contact_information": "Olivia Smith (HR Manager), oliviasmith@stylemakers.com",
        "tags": ["fashion design", "full-time", "New York"],
        "posted_by": "user1022",
        "application_count": 7,
        "job_id": "job1022"
    },
    {
        "job_title": "Social Worker",
        "job_description": "Provide support and assistance to individuals and families in need.",
        "company": "Community Care Services",
        "job_type": "Full-Time",
        "location": "Chicago, IL",
        "salary": "$45,000 - $60,000 per year",
        "application_deadline": "2023-12-05",
        "application_process": "Send your social work degree and resume to hr@communitycare.com",
        "job_requirements": ["Bachelor's degree in Social Work", "Social work experience"],
        "desired_skills": ["Counseling", "Case management"],
        "job_category": "Social Work",
        "date_posted": "2023-11-02",
        "job_status": "Open",
        "contact_information": "James Brown (HR Manager), jamesbrown@communitycare.com",
        "tags": ["social work", "full-time", "Chicago"],
        "posted_by": "user1023",
        "application_count": 6,
        "job_id": "job1023"
    },
    {
        "job_title": "Biomedical Research Scientist",
        "job_description": "Conduct research to advance medical knowledge and develop new treatments.",
        "company": "BioInnovate Research Center",
        "job_type": "Full-Time",
        "location": "Boston, MA",
        "salary": "$80,000 - $100,000 per year",
        "application_deadline": "2023-12-15",
        "application_process": "Submit your biomedical research degree and resume to hr@bioinnovate.com",
        "job_requirements": ["Ph.D. in Biomedical Science", "Research experience"],
        "desired_skills": ["Laboratory work", "Data analysis"],
        "job_category": "Biomedical Research",
        "date_posted": "2023-11-03",
        "job_status": "Open",
        "contact_information": "Dr. Rachel Miller (HR Manager), rachelmiller@bioinnovate.com",
        "tags": ["biomedical research", "full-time", "Boston"],
        "posted_by": "user1024",
        "application_count": 7,
        "job_id": "job1024"
    },
    {
        "job_title": "Fitness Instructor",
        "job_description": "Lead fitness classes and assist clients in achieving their health goals.",
        "company": "FitLife Wellness Center",
        "job_type": "Part-Time",
        "location": "San Francisco, CA",
        "salary": "Hourly rate, commensurate with experience",
        "application_deadline": "2023-12-20",
        "application_process": "Submit your fitness instructor certification and resume to hr@fitlife.com",
        "job_requirements": ["Certified Fitness Instructor", "Fitness training experience"],
        "desired_skills": ["Group fitness", "Personal coaching"],
        "job_category": "Fitness",
        "date_posted": "2023-11-03",
        "job_status": "Open",
        "contact_information": "Emily Wilson (HR Manager), emilywilson@fitlife.com",
        "tags": ["fitness instructor", "part-time", "San Francisco"],
        "posted_by": "user1025",
        "application_count": 5,
        "job_id": "job1025"
    },
    {
        "job_title": "Architect",
        "job_description": "Design and plan architectural structures and buildings.",
        "company": "Cityscape Architects",
        "job_type": "Full-Time",
        "location": "Denver, CO",
        "salary": "$70,000 - $90,000 per year",
        "application_deadline": "2023-12-25",
        "application_process": "Send your architectural portfolio and resume to hr@cityscape.com",
        "job_requirements": ["Bachelor's degree in Architecture", "Architectural design experience"],
        "desired_skills": ["Blueprints", "Building codes"],
        "job_category": "Architecture",
        "date_posted": "2023-11-04",
        "job_status": "Open",
        "contact_information": "Robert Smith (HR Manager), robertsmith@cityscape.com",
        "tags": ["architect", "full-time", "Denver"],
        "posted_by": "user1026",
        "application_count": 8,
        "job_id": "job1026"
    },
    {
        "job_title": "Museum Curator",
        "job_description": "Preserve and curate museum collections and exhibits.",
        "company": "Cultural Heritage Museum",
        "job_type": "Full-Time",
        "location": "New Orleans, LA",
        "salary": "$50,000 - $70,000 per year",
        "application_deadline": "2023-12-30",
        "application_process": "Submit your museum studies degree and resume to hr@culturalmuseum.com",
        "job_requirements": ["Master's degree in Museum Studies", "Curator experience"],
        "desired_skills": ["Exhibit curation", "Art preservation"],
        "job_category": "Museum and Culture",
        "date_posted": "2023-11-04",
        "job_status": "Open",
        "contact_information": "Laura Davis (HR Manager), lauradavis@culturalmuseum.com",
        "tags": ["museum curator", "full-time", "New Orleans"],
        "posted_by": "user1027",
        "application_count": 6,
        "job_id": "job1027"
    },
    {
        "job_title": "Aircraft Mechanic",
        "job_description": "Inspect, repair, and maintain aircraft to ensure safe operation.",
        "company": "SkyTech Aviation Services",
        "job_type": "Full-Time",
        "location": "Dallas, TX",
        "salary": "$60,000 - $80,000 per year",
        "application_deadline": "2023-12-18",
        "application_process": "Send your aircraft mechanic certification and resume to hr@skytech.com",
        "job_requirements": ["Aircraft mechanic certification", "Aircraft maintenance experience"],
        "desired_skills": ["Aircraft inspections", "Repair expertise"],
        "job_category": "Aviation",
        "date_posted": "2023-11-05",
        "job_status": "Open",
        "contact_information": "Daniel Brown (HR Manager), danielbrown@skytech.com",
        "tags": ["aircraft mechanic", "full-time", "Dallas"],
        "posted_by": "user1028",
        "application_count": 7,
        "job_id": "job1028"
    },
    {
        "job_title": "French Language Instructor",
        "job_description": "Teach French language to learners of all levels.",
        "company": "French Language Institute",
        "job_type": "Part-Time",
        "location": "Paris, France",
        "salary": "Hourly rate, commensurate with experience",
        "application_deadline": "2023-12-08",
        "application_process": "Submit your teaching credentials and resume to hr@frenchinstitute.com",
        "job_requirements": ["Teaching certification", "French language proficiency"],
        "desired_skills": ["Language instruction", "Communication skills"],
        "job_category": "Education",
        "date_posted": "2023-11-06",
        "job_status": "Open",
        "contact_information": "Marie Leclerc (HR Manager), marieleclerc@frenchinstitute.com",
        "tags": ["french language instructor", "part-time", "Paris"],
        "posted_by": "user1029",
        "application_count": 8,
        "job_id": "job1029"
    },
    {
        "job_title": "Baker/Pâtissier",
        "job_description": "Create delicious pastries and bread in a bakery in Lyon.",
        "company": "Lyon Bakery & Pâtisserie",
        "job_type": "Full-Time",
        "location": "Lyon, France",
        "salary": "€30,000 - €40,000 per year",
        "application_deadline": "2023-12-12",
        "application_process": "Send your bakery certification and resume to hr@lyonbakery.com",
        "job_requirements": ["Bakery certification", "Baking experience"],
        "desired_skills": ["Pastry making", "Bread baking"],
        "job_category": "Culinary",
        "date_posted": "2023-11-06",
        "job_status": "Open",
        "contact_information": "Pierre Dubois (HR Manager), pierredubois@lyonbakery.com",
        "tags": ["baker", "full-time", "Lyon"],
        "posted_by": "user1030",
        "application_count": 6,
        "job_id": "job1030"
    },
    {
        "job_title": "Tour Guide",
        "job_description": "Lead tours and provide historical insights to tourists in Nice.",
        "company": "French Riviera Tours",
        "job_type": "Seasonal",
        "location": "Nice, France",
        "salary": "Seasonal compensation",
        "application_deadline": "2023-12-10",
        "application_process": "Submit your tour guide experience and resume to hr@rivieratours.com",
        "job_requirements": ["Tour guide experience", "Language proficiency"],
        "desired_skills": ["Tour narration", "Customer service"],
        "job_category": "Tourism",
        "date_posted": "2023-11-07",
        "job_status": "Open",
        "contact_information": "Sophie Martin (HR Manager), sophiemartin@rivieratours.com",
        "tags": ["tour guide", "seasonal", "Nice"],
        "posted_by": "user1031",
        "application_count": 7,
        "job_id": "job1031"
    },
    {
        "job_title": "Wine Sommelier",
        "job_description": "Curate and present wine selections at a restaurant in Bordeaux.",
        "company": "Château de Bordeaux",
        "job_type": "Full-Time",
        "location": "Bordeaux, France",
        "salary": "€40,000 - €50,000 per year",
        "application_deadline": "2023-12-05",
        "application_process": "Send your sommelier certification and resume to hr@bordeauxchateau.com",
        "job_requirements": ["Sommelier certification", "Wine expertise"],
        "desired_skills": ["Wine pairing", "Cellar management"],
        "job_category": "Culinary",
        "date_posted": "2023-11-07",
        "job_status": "Open",
        "contact_information": "Jean-Luc Dupont (HR Manager), jeanlucdupont@bordeauxchateau.com",
        "tags": ["wine sommelier", "full-time", "Bordeaux"],
        "posted_by": "user1032",
        "application_count": 6,
        "job_id": "job1032"
    },
    {
        "job_title": "Art Gallery Curator",
        "job_description": "Curate and manage art exhibitions at a gallery in Paris.",
        "company": "Paris Art Gallery",
        "job_type": "Full-Time",
        "location": "Paris, France",
        "salary": "€35,000 - €45,000 per year",
        "application_deadline": "2023-12-18",
        "application_process": "Submit your art curator experience and resume to hr@parisgallery.com",
        "job_requirements": ["Curator experience", "Art knowledge"],
        "desired_skills": ["Exhibition planning", "Art curation"],
        "job_category": "Art and Culture",
        "date_posted": "2023-11-08",
        "job_status": "Open",
        "contact_information": "Isabelle Martin (HR Manager), isabellemartin@parisgallery.com",
        "tags": ["art gallery curator", "full-time", "Paris"],
        "posted_by": "user1033",
        "application_count": 7,
        "job_id": "job1033"
    },
    {
        "job_title": "Hotel Concierge",
        "job_description": "Assist hotel guests with their needs and provide local recommendations in Marseille.",
        "company": "Marseille Grand Hotel",
        "job_type": "Full-Time",
        "location": "Marseille, France",
        "salary": "€25,000 - €35,000 per year",
        "application_deadline": "2023-12-22",
        "application_process": "Submit your hospitality experience and resume to hr@marseillehotel.com",
        "job_requirements": ["Hospitality experience", "Customer service skills"],
        "desired_skills": ["Concierge services", "Local knowledge"],
        "job_category": "Hospitality",
        "date_posted": "2023-11-08",
        "job_status": "Open",
        "contact_information": "Pierre Lefebvre (HR Manager), pierrelefebvre@marseillehotel.com",
        "tags": ["hotel concierge", "full-time", "Marseille"],
        "posted_by": "user1034",
        "application_count": 6,
        "job_id": "job1034"
    },
    {
        "job_title": "Vineyard Worker",
        "job_description": "Work in a vineyard in the Bordeaux wine region, assisting with grape harvesting and vine care.",
        "company": "Château des Vignes",
        "job_type": "Seasonal",
        "location": "Bordeaux, France",
        "salary": "Seasonal compensation",
        "application_deadline": "2023-12-25",
        "application_process": "Submit your vineyard work experience and resume to hr@bordeauxvignes.com",
        "job_requirements": ["Vineyard work experience", "Physical fitness"],
        "desired_skills": ["Grape harvesting", "Vine care"],
        "job_category": "Agriculture",
        "date_posted": "2023-11-09",
        "job_status": "Open",
        "contact_information": "Claire Durand (HR Manager), clairedurand@bordeauxvignes.com",
        "tags": ["vineyard worker", "seasonal", "Bordeaux"],
        "posted_by": "user1035",
        "application_count": 7,
        "job_id": "job1035"
    },
    {
        "job_title": "Fashion Stylist",
        "job_description": "Style and coordinate fashion looks for photoshoots and events in Paris.",
        "company": "Paris Vogue Styling",
        "job_type": "Full-Time",
        "location": "Paris, France",
        "salary": "€30,000 - €40,000 per year",
        "application_deadline": "2023-12-30",
        "application_process": "Submit your styling portfolio and resume to hr@voguestyling.com",
        "job_requirements": ["Fashion styling experience", "Creativity"],
        "desired_skills": ["Fashion coordination", "Trend awareness"],
        "job_category": "Fashion",
        "date_posted": "2023-11-09",
        "job_status": "Open",
        "contact_information": "Sophie Leclerc (HR Manager), sophieleclerc@voguestyling.com",
        "tags": ["fashion stylist", "full-time", "Paris"],
        "posted_by": "user1036",
        "application_count": 6,
        "job_id": "job1036"
    },
    {
        "job_title": "Gourmet Chef",
        "job_description": "Create exquisite dishes in a fine dining restaurant in Lyon.",
        "company": "Lyon Gourmet Bistro",
        "job_type": "Full-Time",
        "location": "Lyon, France",
        "salary": "€45,000 - €60,000 per year",
        "application_deadline": "2023-12-08",
        "application_process": "Send your culinary portfolio and resume to hr@lyongourmet.com",
        "job_requirements": ["Culinary degree", "Chef experience"],
        "desired_skills": ["Gourmet cooking", "Menu creation"],
        "job_category": "Culinary",
        "date_posted": "2023-11-10",
        "job_status": "Open",
        "contact_information": "Lucas Martin (HR Manager), lucasmartin@lyongourmet.com",
        "tags": ["gourmet chef", "full-time", "Lyon"],
        "posted_by": "user1037",
        "application_count": 8,
        "job_id": "job1037"
    },
    {
        "job_title": "Software Engineer",
        "job_description": "Develop and maintain software applications for a tech startup in Paris.",
        "company": "TechCo Paris",
        "job_type": "Full-Time",
        "location": "Paris, France",
        "salary": "€45,000 - €65,000 per year",
        "application_deadline": "2023-12-08",
        "application_process": "Submit your resume and coding portfolio to hr@techcoparis.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "Software development experience"],
        "desired_skills": ["Programming", "Problem-solving"],
        "job_category": "Software Engineering",
        "date_posted": "2023-11-11",
        "job_status": "Open",
        "contact_information": "Sophie Martin (HR Manager), sophiemartin@techcoparis.com",
        "tags": ["software engineer", "full-time", "Paris"],
        "posted_by": "user1038",
        "application_count": 8,
        "job_id": "job1038"
    },
    {
        "job_title": "Data Analyst",
        "job_description": "Analyze and interpret data to provide insights and recommendations for a data analytics firm in Lyon.",
        "company": "Data Insights Lyon",
        "job_type": "Full-Time",
        "location": "Lyon, France",
        "salary": "€40,000 - €60,000 per year",
        "application_deadline": "2023-12-12",
        "application_process": "Send your data analysis portfolio and resume to hr@datalyon.com",
        "job_requirements": ["Bachelor's degree in Data Science", "Data analysis experience"],
        "desired_skills": ["Data interpretation", "Data visualization"],
        "job_category": "Data Analytics",
        "date_posted": "2023-11-11",
        "job_status": "Open",
        "contact_information": "Pierre Dupont (HR Manager), pierredupont@datalyon.com",
        "tags": ["data analyst", "full-time", "Lyon"],
        "posted_by": "user1039",
        "application_count": 6,
        "job_id": "job1039"
    },
    {
        "job_title": "Network Administrator",
        "job_description": "Manage and maintain network infrastructure for a technology company in Nice.",
        "company": "Tech Solutions Nice",
        "job_type": "Full-Time",
        "location": "Nice, France",
        "salary": "€40,000 - €55,000 per year",
        "application_deadline": "2023-12-10",
        "application_process": "Submit your network administration experience and resume to hr@techsolutionsnice.com",
        "job_requirements": ["Bachelor's degree in Network Administration", "Network administration experience"],
        "desired_skills": ["Network troubleshooting", "Network security"],
        "job_category": "Network Administration",
        "date_posted": "2023-11-12",
        "job_status": "Open",
        "contact_information": "Sophie Lefebvre (HR Manager), sophielefebvre@techsolutionsnice.com",
        "tags": ["network administrator", "full-time", "Nice"],
        "posted_by": "user1040",
        "application_count": 7,
        "job_id": "job1040"
    },
    {
        "job_title": "Web Developer",
        "job_description": "Design and develop websites for clients at a web development agency in Bordeaux.",
        "company": "Bordeaux Web Solutions",
        "job_type": "Full-Time",
        "location": "Bordeaux, France",
        "salary": "€35,000 - €50,000 per year",
        "application_deadline": "2023-12-05",
        "application_process": "Send your web development portfolio and resume to hr@bordeauxwebsolutions.com",
        "job_requirements": ["Bachelor's degree in Web Development", "Web development experience"],
        "desired_skills": ["Front-end development", "Responsive design"],
        "job_category": "Web Development",
        "date_posted": "2023-11-12",
        "job_status": "Open",
        "contact_information": "Lucas Dupont (HR Manager), lucasdupont@bordeauxwebsolutions.com",
        "tags": ["web developer", "full-time", "Bordeaux"],
        "posted_by": "user1041",
        "application_count": 6,
        "job_id": "job1041"
    },
    {
        "job_title": "Cybersecurity Analyst",
        "job_description": "Protect and secure digital assets for a financial institution in Marseille.",
        "company": "Marseille Financial Security",
        "job_type": "Full-Time",
        "location": "Marseille, France",
        "salary": "€50,000 - €70,000 per year",
        "application_deadline": "2023-12-18",
        "application_process": "Submit your cybersecurity experience and resume to hr@marseillesecurity.com",
        "job_requirements": ["Bachelor's degree in Cybersecurity", "Cybersecurity analysis experience"],
        "desired_skills": ["Security monitoring", "Incident response"],
        "job_category": "Cybersecurity",
        "date_posted": "2023-11-13",
        "job_status": "Open",
        "contact_information": "Pierre Martin (HR Manager), pierremartin@marseillesecurity.com",
        "tags": ["cybersecurity analyst", "full-time", "Marseille"],
        "posted_by": "user1042",
        "application_count": 7,
        "job_id": "job1042"
    },
    {
        "job_title": "Database Administrator",
        "job_description": "Manage and maintain databases for a technology company in Paris.",
        "company": "TechDB Paris",
        "job_type": "Full-Time",
        "location": "Paris, France",
        "salary": "€45,000 - €60,000 per year",
        "application_deadline": "2023-12-22",
        "application_process": "Submit your database administration experience and resume to hr@techdbparis.com",
        "job_requirements": ["Bachelor's degree in Database Administration", "Database administration experience"],
        "desired_skills": ["Database maintenance", "Data optimization"],
        "job_category": "Database Administration",
        "date_posted": "2023-11-13",
        "job_status": "Open",
        "contact_information": "Sophie Dupont (HR Manager), sophiedupont@techdbparis.com",
        "tags": ["database administrator", "full-time", "Paris"],
        "posted_by": "user1043",
        "application_count": 8,
        "job_id": "job1043"
    },
    {
        "job_title": "AI Research Scientist",
        "job_description": "Conduct research in artificial intelligence and machine learning for a research institute in Lyon.",
        "company": "Lyon AI Research Institute",
        "job_type": "Full-Time",
        "location": "Lyon, France",
        "salary": "€55,000 - €75,000 per year",
        "application_deadline": "2023-12-30",
        "application_process": "Send your AI research experience and resume to hr@lyonairesearch.com",
        "job_requirements": ["Ph.D. in AI or related field", "AI research experience"],
        "desired_skills": ["Machine learning", "Algorithm development"],
        "job_category": "AI Research",
        "date_posted": "2023-11-14",
        "job_status": "Open",
        "contact_information": "Pierre Martin (HR Manager), pierremartin@lyonairesearch.com",
        "tags": ["AI research scientist", "full-time", "Lyon"],
        "posted_by": "user1044",
        "application_count": 7,
        "job_id": "job1044"
    },
    {
        "job_title": "IT Project Manager",
        "job_description": "Manage IT projects and ensure successful project delivery for a tech firm in Nice.",
        "company": "TechProjex Nice",
        "job_type": "Full-Time",
        "location": "Nice, France",
        "salary": "€50,000 - €70,000 per year",
        "application_deadline": "2023-12-25",
        "application_process": "Submit your IT project management experience and resume to hr@techprojexnice.com",
        "job_requirements": ["Bachelor's degree in IT Management", "IT project management experience"],
        "desired_skills": ["Project planning", "Team coordination"],
        "job_category": "IT Project Management",
        "date_posted": "2023-11-14",
        "job_status": "Open",
        "contact_information": "Sophie Lefebvre (HR Manager), sophielefebvre@techprojexnice.com",
        "tags": ["IT project manager", "full-time", "Nice"],
        "posted_by": "user1045",
        "application_count": 6,
        "job_id": "job1045"
    },
    {
        "job_title": "Cloud Solutions Architect",
        "job_description": "Design and implement cloud solutions for a tech company in Bordeaux.",
        "company": "Bordeaux Cloud Services",
        "job_type": "Full-Time",
        "location": "Bordeaux, France",
        "salary": "€60,000 - €80,000 per year",
        "application_deadline": "2023-12-08",
        "application_process": "Send your cloud architecture experience and resume to hr@bordeauxcloud.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "Cloud architecture experience"],
        "desired_skills": ["Cloud platform expertise", "Scalability planning"],
        "job_category": "Cloud Computing",
        "date_posted": "2023-11-15",
        "job_status": "Open",
        "contact_information": "Lucas Dupont (HR Manager), lucasdupont@bordeauxcloud.com",
        "tags": ["cloud solutions architect", "full-time", "Bordeaux"],
        "posted_by": "user1046",
        "application_count": 8,
        "job_id": "job1046"
    },
    {
        "job_title": "Software Tester",
        "job_description": "Test software applications and identify defects for a software development company in Marseille.",
        "company": "Marseille Software Testing",
        "job_type": "Full-Time",
        "location": "Marseille, France",
        "salary": "€40,000 - €55,000 per year",
        "application_deadline": "2023-12-12",
        "application_process": "Submit your software testing experience and resume to hr@marseilletesting.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "Software testing experience"],
        "desired_skills": ["Test case design", "Bug tracking"],
        "job_category": "Software Testing",
        "date_posted": "2023-11-15",
        "job_status": "Open",
        "contact_information": "Pierre Martin (HR Manager), pierremartin@marseilletesting.com",
        "tags": ["software tester", "full-time", "Marseille"],
        "posted_by": "user1047",
        "application_count": 7,
        "job_id": "job1047"
    },
    {
        "job_title": "Machine Learning Engineer",
        "job_description": "Develop machine learning models for an AI research institute in Paris.",
        "company": "AI Innovations Paris",
        "job_type": "Full-Time",
        "location": "Paris, France",
        "salary": "€50,000 - €70,000 per year",
        "application_deadline": "2023-12-10",
        "application_process": "Send your machine learning experience and resume to hr@aiinnovationsparis.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "Machine learning experience"],
        "desired_skills": ["Machine learning algorithms", "Data analysis"],
        "job_category": "Machine Learning",
        "date_posted": "2023-11-16",
        "job_status": "Open",
        "contact_information": "Sophie Dupont (HR Manager), sophiedupont@aiinnovationsparis.com",
        "tags": ["machine learning engineer", "full-time", "Paris"],
        "posted_by": "user1048",
        "application_count": 6,
        "job_id": "job1048"
    },
    {
        "job_title": "DevOps Engineer",
        "job_description": "Implement and manage DevOps practices for a tech company in Lyon.",
        "company": "Lyon DevOps Solutions",
        "job_type": "Full-Time",
        "location": "Lyon, France",
        "salary": "€45,000 - €65,000 per year",
        "application_deadline": "2023-12-18",
        "application_process": "Submit your DevOps experience and resume to hr@lyondevops.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "DevOps experience"],
        "desired_skills": ["Continuous integration", "Containerization"],
        "job_category": "DevOps",
        "date_posted": "2023-11-16",
        "job_status": "Open",
        "contact_information": "Pierre Martin (HR Manager), pierremartin@lyondevops.com",
        "tags": ["devops engineer", "full-time", "Lyon"],
        "posted_by": "user1049",
        "application_count": 7,
        "job_id": "job1049"
    },
    {
        "job_title": "Front-End Developer",
        "job_description": "Design and implement user interfaces for web applications at a tech firm in Nice.",
        "company": "TechUI Nice",
        "job_type": "Full-Time",
        "location": "Nice, France",
        "salary": "€40,000 - €55,000 per year",
        "application_deadline": "2023-12-22",
        "application_process": "Send your front-end development portfolio and resume to hr@techuinice.com",
        "job_requirements": ["Bachelor's degree in Web Development", "Front-end development experience"],
        "desired_skills": ["UI design", "Responsive web design"],
        "job_category": "Front-End Development",
        "date_posted": "2023-11-17",
        "job_status": "Open",
        "contact_information": "Sophie Lefebvre (HR Manager), sophielefebvre@techuinice.com",
        "tags": ["front-end developer", "full-time", "Nice"],
        "posted_by": "user1050",
        "application_count": 8,
        "job_id": "job1050"
    },
    {
        "job_title": "Database Developer",
        "job_description": "Design and develop databases for a tech company in Bordeaux.",
        "company": "Bordeaux Database Solutions",
        "job_type": "Full-Time",
        "location": "Bordeaux, France",
        "salary": "€45,000 - €60,000 per year",
        "application_deadline": "2023-12-25",
        "application_process": "Submit your database development experience and resume to hr@bordeauxdatabases.com",
        "job_requirements": ["Bachelor's degree in Database Development", "Database development experience"],
        "desired_skills": ["Database design", "Query optimization"],
        "job_category": "Database Development",
        "date_posted": "2023-11-17",
        "job_status": "Open",
        "contact_information": "Lucas Dupont (HR Manager), lucasdupont@bordeauxdatabases.com",
        "tags": ["database developer", "full-time", "Bordeaux"],
        "posted_by": "user1051",
        "application_count": 6,
        "job_id": "job1051"
    },
    {
        "job_title": "Software Developer",
        "job_description": "Design and develop software applications for a tech company in Toronto, Canada.",
        "company": "TechSolutions Canada",
        "job_type": "Full-Time",
        "location": "Toronto, Canada",
        "salary": "C$60,000 - C$80,000 per year",
        "application_deadline": "2023-12-08",
        "application_process": "Submit your resume and coding portfolio to hr@techsolutionscanada.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "Software development experience"],
        "desired_skills": ["Programming", "Problem-solving"],
        "job_category": "Software Development",
        "date_posted": "2023-11-20",
        "job_status": "Open",
        "contact_information": "Sophie Martin (HR Manager), sophiemartin@techsolutionscanada.com",
        "tags": ["software developer", "full-time", "Toronto"],
        "posted_by": "user1052",
        "application_count": 8,
        "job_id": "job1052"
    },
    {
        "job_title": "Data Scientist",
        "job_description": "Analyze and interpret data to provide insights for a data analytics firm in Sydney, Australia.",
        "company": "Data Insights Sydney",
        "job_type": "Full-Time",
        "location": "Sydney, Australia",
        "salary": "A$70,000 - A$90,000 per year",
        "application_deadline": "2023-12-12",
        "application_process": "Send your data analysis portfolio and resume to hr@datasydney.com",
        "job_requirements": ["Bachelor's degree in Data Science", "Data analysis experience"],
        "desired_skills": ["Data interpretation", "Data visualization"],
        "job_category": "Data Analytics",
        "date_posted": "2023-11-20",
        "job_status": "Open",
        "contact_information": "Pierre Dupont (HR Manager), pierredupont@datasydney.com",
        "tags": ["data scientist", "full-time", "Sydney"],
        "posted_by": "user1053",
        "application_count": 6,
        "job_id": "job1053"
    },
    {
        "job_title": "Network Engineer",
        "job_description": "Design and manage network infrastructure for a technology company in London, UK.",
        "company": "Tech Solutions London",
        "job_type": "Full-Time",
        "location": "London, UK",
        "salary": "£40,000 - £55,000 per year",
        "application_deadline": "2023-12-10",
        "application_process": "Submit your network engineering experience and resume to hr@techsolutionslondon.com",
        "job_requirements": ["Bachelor's degree in Network Engineering", "Network engineering experience"],
        "desired_skills": ["Network design", "Network security"],
        "job_category": "Network Engineering",
        "date_posted": "2023-11-21",
        "job_status": "Open",
        "contact_information": "Sophie Lefebvre (HR Manager), sophielefebvre@techsolutionslondon.com",
        "tags": ["network engineer", "full-time", "London"],
        "posted_by": "user1054",
        "application_count": 7,
        "job_id": "job1054"
    },
    {
        "job_title": "Web Designer",
        "job_description": "Create visually appealing and user-friendly websites for clients in Mumbai, India.",
        "company": "Mumbai Web Creations",
        "job_type": "Full-Time",
        "location": "Mumbai, India",
        "salary": "₹30,000 - ₹45,000 per month",
        "application_deadline": "2023-12-05",
        "application_process": "Send your web design portfolio and resume to hr@mumbaiweb.com",
        "job_requirements": ["Bachelor's degree in Web Design", "Web design experience"],
        "desired_skills": ["UI/UX design", "Responsive design"],
        "job_category": "Web Design",
        "date_posted": "2023-11-21",
        "job_status": "Open",
        "contact_information": "Lucas Dupont (HR Manager), lucasdupont@mumbaiweb.com",
        "tags": ["web designer", "full-time", "Mumbai"],
        "posted_by": "user1055",
        "application_count": 6,
        "job_id": "job1055"
    },
    {
        "job_title": "Cybersecurity Consultant",
        "job_description": "Provide cybersecurity consulting services for businesses in Berlin, Germany.",
        "company": "Berlin Cybersecurity Consulting",
        "job_type": "Full-Time",
        "location": "Berlin, Germany",
        "salary": "€50,000 - €70,000 per year",
        "application_deadline": "2023-12-18",
        "application_process": "Submit your cybersecurity consulting experience and resume to hr@berlincyber.com",
        "job_requirements": ["Bachelor's degree in Cybersecurity", "Cybersecurity consulting experience"],
        "desired_skills": ["Security assessments", "Security policy development"],
        "job_category": "Cybersecurity",
        "date_posted": "2023-11-22",
        "job_status": "Open",
        "contact_information": "Pierre Martin (HR Manager), pierremartin@berlincyber.com",
        "tags": ["cybersecurity consultant", "full-time", "Berlin"],
        "posted_by": "user1056",
        "application_count": 7,
        "job_id": "job1056"
    },
    {
        "job_title": "Database Administrator",
        "job_description": "Manage and maintain databases for a technology company in Toronto, Canada.",
        "company": "TechDB Toronto",
        "job_type": "Full-Time",
        "location": "Toronto, Canada",
        "salary": "C$60,000 - C$80,000 per year",
        "application_deadline": "2023-12-22",
        "application_process": "Submit your database administration experience and resume to hr@techdbtoronto.com",
        "job_requirements": ["Bachelor's degree in Database Administration", "Database administration experience"],
        "desired_skills": ["Database maintenance", "Data optimization"],
        "job_category": "Database Administration",
        "date_posted": "2023-11-22",
        "job_status": "Open",
        "contact_information": "Sophie Dupont (HR Manager), sophiedupont@techdbtoronto.com",
        "tags": ["database administrator", "full-time", "Toronto"],
        "posted_by": "user1057",
        "application_count": 8,
        "job_id": "job1057"
    },
    {
        "job_title": "AI Research Scientist",
        "job_description": "Conduct research in artificial intelligence and machine learning for a research institute in Sydney, Australia.",
        "company": "Sydney AI Research Institute",
        "job_type": "Full-Time",
        "location": "Sydney, Australia",
        "salary": "A$80,000 - A$100,000 per year",
        "application_deadline": "2023-12-30",
        "application_process": "Send your AI research experience and resume to hr@sydneyairesearch.com",
        "job_requirements": ["Ph.D. in AI or related field", "AI research experience"],
        "desired_skills": ["Machine learning", "Algorithm development"],
        "job_category": "AI Research",
        "date_posted": "2023-11-23",
        "job_status": "Open",
        "contact_information": "Pierre Martin (HR Manager), pierremartin@sydneyairesearch.com",
        "tags": ["AI research scientist", "full-time", "Sydney"],
        "posted_by": "user1058",
        "application_count": 7,
        "job_id": "job1058"
    },
    {
        "job_title": "IT Project Manager",
        "job_description": "Manage IT projects and ensure successful project delivery for a tech firm in London, UK.",
        "company": "TechProjex London",
        "job_type": "Full-Time",
        "location": "London, UK",
        "salary": "£50,000 - £70,000 per year",
        "application_deadline": "2023-12-25",
        "application_process": "Submit your IT project management experience and resume to hr@techprojexlondon.com",
        "job_requirements": ["Bachelor's degree in IT Management", "IT project management experience"],
        "desired_skills": ["Project planning", "Team coordination"],
        "job_category": "IT Project Management",
        "date_posted": "2023-11-23",
        "job_status": "Open",
        "contact_information": "Sophie Lefebvre (HR Manager), sophielefebvre@techprojexlondon.com",
        "tags": ["IT project manager", "full-time", "London"],
        "posted_by": "user1059",
        "application_count": 6,
        "job_id": "job1059"
    },
    {
        "job_title": "Cloud Solutions Architect",
        "job_description": "Design and implement cloud solutions for a tech company in Sydney, Australia.",
        "company": "Sydney Cloud Services",
        "job_type": "Full-Time",
        "location": "Sydney, Australia",
        "salary": "A$90,000 - A$110,000 per year",
        "application_deadline": "2023-12-08",
        "application_process": "Send your cloud architecture experience and resume to hr@sydneycloud.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "Cloud architecture experience"],
        "desired_skills": ["Cloud platform expertise", "Scalability planning"],
        "job_category": "Cloud Computing",
        "date_posted": "2023-11-24",
        "job_status": "Open",
        "contact_information": "Lucas Dupont (HR Manager), lucasdupont@sydneycloud.com",
        "tags": ["cloud solutions architect", "full-time", "Sydney"],
        "posted_by": "user1060",
        "application_count": 8,
        "job_id": "job1060"
    },
    {
        "job_title": "Software Tester",
        "job_description": "Test software applications and identify defects for a software development company in Berlin, Germany.",
        "company": "Berlin Software Testing",
        "job_type": "Full-Time",
        "location": "Berlin, Germany",
        "salary": "€45,000 - €60,000 per year",
        "application_deadline": "2023-12-12",
        "application_process": "Submit your software testing experience and resume to hr@berlintesting.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "Software testing experience"],
        "desired_skills": ["Test case design", "Bug tracking"],
        "job_category": "Software Testing",
        "date_posted": "2023-11-24",
        "job_status": "Open",
        "contact_information": "Pierre Martin (HR Manager), pierremartin@berlintesting.com",
        "tags": ["software tester", "full-time", "Berlin"],
        "posted_by": "user1061",
        "application_count": 7,
        "job_id": "job1061"
    },
    {
        "job_title": "Machine Learning Engineer",
        "job_description": "Develop machine learning models for an AI research institute in Toronto, Canada.",
        "company": "TechAI Toronto",
        "job_type": "Full-Time",
        "location": "Toronto, Canada",
        "salary": "C$70,000 - C$90,000 per year",
        "application_deadline": "2023-12-10",
        "application_process": "Send your machine learning experience and resume to hr@techaitoronto.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "Machine learning experience"],
        "desired_skills": ["Machine learning algorithms", "Data analysis"],
        "job_category": "Machine Learning",
        "date_posted": "2023-11-25",
        "job_status": "Open",
        "contact_information": "Sophie Dupont (HR Manager), sophiedupont@techaitoronto.com",
        "tags": ["machine learning engineer", "full-time", "Toronto"],
        "posted_by": "user1062",
        "application_count": 6,
        "job_id": "job1062"
    },
    {
        "job_title": "DevOps Engineer",
        "job_description": "Implement and manage DevOps practices for a tech company in Sydney, Australia.",
        "company": "Sydney DevOps Solutions",
        "job_type": "Full-Time",
        "location": "Sydney, Australia",
        "salary": "A$75,000 - A$95,000 per year",
        "application_deadline": "2023-12-18",
        "application_process": "Submit your DevOps experience and resume to hr@sydneydevops.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "DevOps experience"],
        "desired_skills": ["Continuous integration", "Containerization"],
        "job_category": "DevOps",
        "date_posted": "2023-11-25",
        "job_status": "Open",
        "contact_information": "Pierre Martin (HR Manager), pierremartin@sydneydevops.com",
        "tags": ["devops engineer", "full-time", "Sydney"],
        "posted_by": "user1063",
        "application_count": 7,
        "job_id": "job1063"
    },
    {
        "job_title": "Front-End Developer",
        "job_description": "Design and implement user interfaces for web applications at a tech firm in Toronto, Canada.",
        "company": "TechUI Toronto",
        "job_type": "Full-Time",
        "location": "Toronto, Canada",
        "salary": "C$50,000 - C$70,000 per year",
        "application_deadline": "2023-12-22",
        "application_process": "Send your front-end development portfolio and resume to hr@techuitoronto.com",
        "job_requirements": ["Bachelor's degree in Web Development", "Front-end development experience"],
        "desired_skills": ["UI design", "Responsive web design"],
        "job_category": "Front-End Development",
        "date_posted": "2023-11-26",
        "job_status": "Open",
        "contact_information": "Sophie Dupont (HR Manager), sophiedupont@techuitoronto.com",
        "tags": ["front-end developer", "full-time", "Toronto"],
        "posted_by": "user1064",
        "application_count": 8,
        "job_id": "job1064"
    },
    {
        "job_title": "Database Developer",
        "job_description": "Design and develop databases for a tech company in Sydney, Australia.",
        "company": "Sydney Database Solutions",
        "job_type": "Full-Time",
        "location": "Sydney, Australia",
        "salary": "A$60,000 - A$80,000 per year",
        "application_deadline": "2023-12-25",
        "application_process": "Submit your database development experience and resume to hr@sydneydatabases.com",
        "job_requirements": ["Bachelor's degree in Database Development", "Database development experience"],
        "desired_skills": ["Database design", "Query optimization"],
        "job_category": "Database Development",
        "date_posted": "2023-11-26",
        "job_status": "Open",
        "contact_information": "Lucas Dupont (HR Manager), lucasdupont@sydneydatabases.com",
        "tags": ["database developer", "full-time", "Sydney"],
        "posted_by": "user1065",
        "application_count": 6,
        "job_id": "job1065"
    },
    {
        "job_title": "Software Developer",
        "job_description": "Design and develop software applications for a tech company in Toronto, Canada.",
        "company": "TechSolutions Canada",
        "job_type": "Full-Time",
        "location": "Toronto, Canada",
        "salary": "C$60,000 - C$80,000 per year",
        "application_deadline": "2023-12-08",
        "application_process": "Submit your resume and coding portfolio to hr@techsolutionscanada.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "Software development experience"],
        "desired_skills": ["Programming", "Problem-solving"],
        "job_category": "Software Development",
        "date_posted": "2023-11-20",
        "job_status": "Open",
        "contact_information": "Sophie Martin (HR Manager), sophiemartin@techsolutionscanada.com",
        "tags": ["software developer", "full-time", "Toronto"],
        "posted_by": "user1066",
        "application_count": 8,
        "job_id": "job1066"
    },
    {
        "job_title": "Data Scientist",
        "job_description": "Analyze and interpret data to provide insights for a data analytics firm in Sydney, Australia.",
        "company": "Data Insights Sydney",
        "job_type": "Full-Time",
        "location": "Sydney, Australia",
        "salary": "A$70,000 - A$90,000 per year",
        "application_deadline": "2023-12-12",
        "application_process": "Send your data analysis portfolio and resume to hr@datasydney.com",
        "job_requirements": ["Bachelor's degree in Data Science", "Data analysis experience"],
        "desired_skills": ["Data interpretation", "Data visualization"],
        "job_category": "Data Analytics",
        "date_posted": "2023-11-20",
        "job_status": "Open",
        "contact_information": "Pierre Dupont (HR Manager), pierredupont@datasydney.com",
        "tags": ["data scientist", "full-time", "Sydney"],
        "posted_by": "user1067",
        "application_count": 6,
        "job_id": "job1067"
    },
    {
        "job_title": "Network Engineer",
        "job_description": "Design and manage network infrastructure for a technology company in London, UK.",
        "company": "Tech Solutions London",
        "job_type": "Full-Time",
        "location": "London, UK",
        "salary": "£40,000 - £55,000 per year",
        "application_deadline": "2023-12-10",
        "application_process": "Submit your network engineering experience and resume to hr@techsolutionslondon.com",
        "job_requirements": ["Bachelor's degree in Network Engineering", "Network engineering experience"],
        "desired_skills": ["Network design", "Network security"],
        "job_category": "Network Engineering",
        "date_posted": "2023-11-21",
        "job_status": "Open",
        "contact_information": "Sophie Lefebvre (HR Manager), sophielefebvre@techsolutionslondon.com",
        "tags": ["network engineer", "full-time", "London"],
        "posted_by": "user1068",
        "application_count": 7,
        "job_id": "job1068"
    },
    {
        "job_title": "Web Designer",
        "job_description": "Create visually appealing and user-friendly websites for clients in Mumbai, India.",
        "company": "Mumbai Web Creations",
        "job_type": "Full-Time",
        "location": "Mumbai, India",
        "salary": "₹30,000 - ₹45,000 per month",
        "application_deadline": "2023-12-05",
        "application_process": "Send your web design portfolio and resume to hr@mumbaiweb.com",
        "job_requirements": ["Bachelor's degree in Web Design", "Web design experience"],
        "desired_skills": ["UI/UX design", "Responsive design"],
        "job_category": "Web Design",
        "date_posted": "2023-11-21",
        "job_status": "Open",
        "contact_information": "Lucas Dupont (HR Manager), lucasdupont@mumbaiweb.com",
        "tags": ["web designer", "full-time", "Mumbai"],
        "posted_by": "user1069",
        "application_count": 6,
        "job_id": "job1069"
    },
    {
        "job_title": "Cybersecurity Consultant",
        "job_description": "Provide cybersecurity consulting services for businesses in Berlin, Germany.",
        "company": "Berlin Cybersecurity Consulting",
        "job_type": "Full-Time",
        "location": "Berlin, Germany",
        "salary": "€50,000 - €70,000 per year",
        "application_deadline": "2023-12-18",
        "application_process": "Submit your cybersecurity consulting experience and resume to hr@berlincyber.com",
        "job_requirements": ["Bachelor's degree in Cybersecurity", "Cybersecurity consulting experience"],
        "desired_skills": ["Security assessments", "Security policy development"],
        "job_category": "Cybersecurity",
        "date_posted": "2023-11-22",
        "job_status": "Open",
        "contact_information": "Pierre Martin (HR Manager), pierremartin@berlincyber.com",
        "tags": ["cybersecurity consultant", "full-time", "Berlin"],
        "posted_by": "user1070",
        "application_count": 7,
        "job_id": "job1070"
    },
    {
        "job_title": "Database Administrator",
        "job_description": "Manage and maintain databases for a technology company in Toronto, Canada.",
        "company": "TechDB Toronto",
        "job_type": "Full-Time",
        "location": "Toronto, Canada",
        "salary": "C$60,000 - C$80,000 per year",
        "application_deadline": "2023-12-22",
        "application_process": "Submit your database administration experience and resume to hr@techdbtoronto.com",
        "job_requirements": ["Bachelor's degree in Database Administration", "Database administration experience"],
        "desired_skills": ["Database maintenance", "Data optimization"],
        "job_category": "Database Administration",
        "date_posted": "2023-11-22",
        "job_status": "Open",
        "contact_information": "Sophie Dupont (HR Manager), sophiedupont@techdbtoronto.com",
        "tags": ["database administrator", "full-time", "Toronto"],
        "posted_by": "user1071",
        "application_count": 8,
        "job_id": "job1071"
    },
    {
        "job_title": "AI Research Scientist",
        "job_description": "Conduct research in artificial intelligence and machine learning for a research institute in Sydney, Australia.",
        "company": "Sydney AI Research Institute",
        "job_type": "Full-Time",
        "location": "Sydney, Australia",
        "salary": "A$80,000 - A$100,000 per year",
        "application_deadline": "2023-12-30",
        "application_process": "Send your AI research experience and resume to hr@sydneyairesearch.com",
        "job_requirements": ["Ph.D. in AI or related field", "AI research experience"],
        "desired_skills": ["Machine learning", "Algorithm development"],
        "job_category": "AI Research",
        "date_posted": "2023-11-23",
        "job_status": "Open",
        "contact_information": "Pierre Martin (HR Manager), pierremartin@sydneyairesearch.com",
        "tags": ["AI research scientist", "full-time", "Sydney"],
        "posted_by": "user1072",
        "application_count": 7,
        "job_id": "job1072"
    },
    {
        "job_title": "IT Project Manager",
        "job_description": "Manage IT projects and ensure successful project delivery for a tech firm in London, UK.",
        "company": "TechProjex London",
        "job_type": "Full-Time",
        "location": "London, UK",
        "salary": "£50,000 - £70,000 per year",
        "application_deadline": "2023-12-25",
        "application_process": "Submit your IT project management experience and resume to hr@techprojexlondon.com",
        "job_requirements": ["Bachelor's degree in IT Management", "IT project management experience"],
        "desired_skills": ["Project planning", "Team coordination"],
        "job_category": "IT Project Management",
        "date_posted": "2023-11-23",
        "job_status": "Open",
        "contact_information": "Sophie Lefebvre (HR Manager), sophielefebvre@techprojexlondon.com",
        "tags": ["IT project manager", "full-time", "London"],
        "posted_by": "user1073",
        "application_count": 6,
        "job_id": "job1073"
    },
    {
        "job_title": "Cloud Solutions Architect",
        "job_description": "Design and implement cloud solutions for a tech company in Sydney, Australia.",
        "company": "Sydney Cloud Services",
        "job_type": "Full-Time",
        "location": "Sydney, Australia",
        "salary": "A$90,000 - A$110,000 per year",
        "application_deadline": "2023-12-08",
        "application_process": "Send your cloud architecture experience and resume to hr@sydneycloud.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "Cloud architecture experience"],
        "desired_skills": ["Cloud platform expertise", "Scalability planning"],
        "job_category": "Cloud Computing",
        "date_posted": "2023-11-24",
        "job_status": "Open",
        "contact_information": "Lucas Dupont (HR Manager), lucasdupont@sydneycloud.com",
        "tags": ["cloud solutions architect", "full-time", "Sydney"],
        "posted_by": "user1074",
        "application_count": 8,
        "job_id": "job1074"
    },
    {
        "job_title": "Software Tester",
        "job_description": "Test software applications and identify defects for a software development company in Berlin, Germany.",
        "company": "Berlin Software Testing",
        "job_type": "Full-Time",
        "location": "Berlin, Germany",
        "salary": "€45,000 - €60,000 per year",
        "application_deadline": "2023-12-12",
        "application_process": "Submit your software testing experience and resume to hr@berlintesting.com",
        "job_requirements": ["Bachelor's degree in Computer Science", "Software testing experience"],
        "desired_skills": ["Test case design", "Bug tracking"],
        "job_category": "Software Testing",
        "date_posted": "2023-11-24",
        "job_status": "Open",
        "contact_information": "Pierre Martin (HR Manager), pierremartin@berlintesting.com",
        "tags": ["software tester", "full-time", "Berlin"],
        "posted_by": "user1075",
        "application_count": 7,
        "job_id": "job1075"
    }
    
]

if collection.count_documents({}) == 0:
    # Insert the products if they don't exist
    collection.insert_many(jobs)
    print("Products inserted successfully!")




